backend:
  name: github
  repo: Sambox-tm/Sam-Box-Comics
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "comics"
    label: "الكوميكس"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "الوصف", name: "description", widget: "text"}
